# Use root/example as user/password credentials
version: "2.3"

services:

  db:
    build: "./database"
    command: --default-authentication-plugin=mysql_native_password --init-file=/home/db_create.sql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: pass
    expose:
      - 3306

  metrics_exporter:
    build: "./metrics_exporter"
    restart: always
    command: -event_file_path /data/model_cp/ssd_mobilenet_v1_coco/model/eval/events.out.tfevents.1558898568.6acf4ea16b37
    environment:
      DB_HOST: "db"
      DB_PORT: 3306
      DB_USER: "root"
      DB_PASS: "pass"
      DB_DATABASE: "prod"
    depends_on:
      - db
    volumes: 
      - /home/tanderson/graduateWork/project/framework/data:/data

  # ssd_mobilenet_v1_coco:
  #   build: "./tensorflow_test_model"
  #   runtime: nvidia
  #   restart: "no"
  #   command: python object_detection/model_main.py -model_dir /data/model_cp/ssd_mobilenet_v1_coco/model -pipeline_config_path object_detection/samples/configs/ssd_mobilenet_v1_coco.config -num_train_steps 200 -checkpoint_dir /data/model_cp/ssd_mobilenet_v1_coco/model
  #   volumes: 
  #     - /home/tanderson/graduateWork/project/framework/data:/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
