# Use root/example as user/password credentials
version: "2.3"

services:
    generate_data:
      build: "../services/tensorflow_test_model"
      runtime: nvidia
      restart: "no"
      command: python object_detection/dataset_tools/create_coco_tf_record.py --logtostderr --include_masks --train_image_dir=/data/raw-data/train2017 --val_image_dir=/data/raw-data/val2017 --test_image_dir=/data/raw-data/test2017 --train_annotations_file=/data/annos/small_train.json --val_annotations_file=/data/annos/small_val.json --testdev_annotations_file=/data/raw-data/annotations/image_info_test-dev2017.json --output_dir=/data/small_dataset
      volumes: 
        - /home/tanderson/models/datasets/mscoco:/data