# Use root/example as user/password credentials
version: "2.3"

services:
    generate_data:
      build: "../services/tensorflow_test_model"
      runtime: nvidia
      restart: "no"
      command: python object_detection/dataset_tools/create_coco_tf_record.py --logtostderr --include_masks --train_image_dir=/data/generated_split/train --val_image_dir=/data/generated_split/val --test_image_dir=/data/test2017 --train_annotations_file=/data/generated_annotations/train_annotations.json --val_annotations_file=/data/generated_annotations/val_annotations.json --testdev_annotations_file=/data/raw-data/annotations_2017/image_info_test-dev2017.json --output_dir=/data/coco_records/
      volumes: 
        - /home/tanderson/models/datasets/mscoco/raw-data:/data