# Use root/example as user/password credentials
version: "2.3"

services:
  ssd_mobilenet_v1_coco:
    build: "../services/tensorflow_test_model"
    runtime: nvidia
    restart: "no"
    command: python object_detection/model_main.py -model_dir /runs/ssd_mobilenet_v2_minival2014_coco -pipeline_config_path /configs/ssd_mobilenet_v2_minival2014_coco.config
    volumes: 
      - /home/tanderson/models/datasets/mscoco/raw-data:/data
      - /home/tanderson/models/runs:/runs
      - /home/tanderson/git/deep-frame/configs:/configs